name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment for manual deployment"
        required: true
        default: "TST"
        type: choice
        options:
          - TST

env:
  TF_VERSION: "1.5.0"

jobs:
  terraform-validate:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  plan-tst:
    name: Plan TST Deployment
    runs-on: ubuntu-latest
    needs: terraform-validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        env:
          # Add your backend configuration here
          TF_BACKEND_CONFIG: ${{ secrets.TF_BACKEND_CONFIG_TST }}

      - name: Terraform Plan TST
        run: terraform plan -var-file="environments/tst.tfvars" -out=tst.tfplan
        env:
          # Add your cloud provider credentials here
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tst-terraform-plan
          path: tst.tfplan
          retention-days: 30

  deploy-tst:
    name: Deploy to TST Environment
    runs-on: ubuntu-latest
    needs: plan-tst
    environment: TST

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tst-terraform-plan

      - name: Terraform Init
        run: terraform init
        env:
          TF_BACKEND_CONFIG: ${{ secrets.TF_BACKEND_CONFIG_TST }}

      - name: Terraform Apply TST
        run: terraform apply -auto-approve tst.tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  plan-prd:
    name: Plan PRD Deployment
    runs-on: ubuntu-latest
    needs: deploy-tst
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        env:
          TF_BACKEND_CONFIG: ${{ secrets.TF_BACKEND_CONFIG_PRD }}

      - name: Terraform Plan PRD
        run: terraform plan -var-file="environments/prd.tfvars" -out=prd.tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prd-terraform-plan
          path: prd.tfplan
          retention-days: 30

  deploy-prd:
    name: Deploy to PRD Environment
    runs-on: ubuntu-latest
    needs: plan-prd
    if: github.ref == 'refs/heads/main'
    environment: PRD

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: prd-terraform-plan

      - name: Terraform Init
        run: terraform init
        env:
          TF_BACKEND_CONFIG: ${{ secrets.TF_BACKEND_CONFIG_PRD }}

      - name: Terraform Apply PRD
        run: terraform apply -auto-approve prd.tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
